@SAP_Backend_HostAddress = https://localhost:7155


GET {{SAP_Backend_HostAddress}}/api/teams

###



POST {{SAP_Backend_HostAddress}}/api/teams
Content-Type: application/json

{
  "Id": 0,
  "Round": 2,
  "Wins": 1,
  "PetIds": [
    "Turtle",
    "Turtle",
    "Turtle",
    "Turtle",
    "Turtle"
  ]
}

###
